language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script:
  - psql -c 'create database test;' -U postgres
  - python server.py &  # start a Web server in the background
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - nosetests

after_success:
  - codecov

env:
  - TEST='True'

services:
  - postgresql
  - availability-monitoring-auto
  - continuous-delivery-nyu-delta-team-f17
  - elephantsql-nyu-delta-team-f17


