from flask_restplus import Api, fields
from server import app
######################################################################
# Configure Swagger before initializing it
######################################################################
api = Api(app,
          version='1.0.0',
          title='Recommendation Demo REST API Service',
          description='This is a sample server Recommendation server.',
          doc='/apidocs/'
          )

# This namespace is the start of the path i.e., /recommendations
ns = api.namespace('recommendations', description='Recommendation operations')

rec_type_model = api.model('RecommendationType', {
    'id': fields.Integer(readOnly=True,
                         description='The unique id assigned internally by service'),
    'name': fields.String(required=True,
                          description="Name of Recommendation"),
    'is_active': fields.Boolean(required=True,
                          description='Active status')
})

# Define the model so that the docs reflect what can be sent
recommendation_model = api.model('Recommendation', {
    'id': fields.Integer(readOnly=True,
                         description='The unique id assigned internally by service'),
    'product_id': fields.Integer(required=True,
                         description='The id of the product that a recommendation will be created for'),
    'rec_type_id': fields.Integer(required=True,
                         description='The unique id of the recommendation type.'),
    'rec_product_id': fields.Integer(required=True,
                         description='The id of the product that is being recommended'),
    'weight': fields.Float(required=True,
                         description='The calculated weight generated by the Algorithm \
                                        quantifying the quality of the recommendation'),
    'rec_type': fields.Nested(
        api.models['RecommendationType'],
        required=False,
        description='Recommendation Type Relationship'
    )
})

expected_create_model  = api.model('Recommendation', {
    'product_id': fields.Integer(required=True,
                         description='The id of the product that a recommendation will be created for'),
    'rec_type_id': fields.Integer(required=True,
                         description='The unique id of the recommendation type.'),
    'rec_product_id': fields.Integer(required=True,
                         description='The id of the product that is being recommended'),
    'weight': fields.Float(required=True,
                         description='The calculated weight generated by the Algorithm \
                                        quantifying the quality of the recommendation')
})